<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2492" started-at="2014-06-13T06:16:44Z" finished-at="2014-06-13T06:16:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2492" started-at="2014-06-13T06:16:44Z" finished-at="2014-06-13T06:16:46Z">
      <class name="com.atmecs.EmployeeManagementTest.StoryRunner">
        <test-method status="FAIL" signature="run()[pri:0, instance:com.atmecs.EmployeeManagementTest.StoryRunner@1d8dd769]" name="run" duration-ms="2483" started-at="2014-06-13T11:46:44Z" finished-at="2014-06-13T11:46:46Z">
          <exception class="org.jbehave.core.embedder.Embedder$RunningStoriesFailed">
            <message>
              <![CDATA[Failures in running stories: ReportsCount[stories=1,storiesNotAllowed=0,storiesPending=0,scenarios=58,scenariosFailed=55,scenariosNotAllowed=0,scenariosPending=0,stepsFailed=55]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: ReportsCount[stories=1,storiesNotAllowed=0,storiesPending=0,scenarios=58,scenariosFailed=55,scenariosNotAllowed=0,scenariosPending=0,stepsFailed=55]
	at org.jbehave.core.embedder.Embedder$ThrowingRunningStoriesFailed.handleFailures(Embedder.java:525)
	at org.jbehave.core.embedder.Embedder.handleFailures(Embedder.java:269)
	at org.jbehave.core.embedder.Embedder.generateReportsView(Embedder.java:256)
	at org.jbehave.core.embedder.Embedder.generateReportsView(Embedder.java:237)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
	at org.jbehave.core.junit.JUnitStory.run(JUnitStory.java:24)
	at com.atmecs.EmployeeManagementTest.StoryRunner.run(StoryRunner.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.jbehave.core.embedder.Embedder$RunningStoriesFailed -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run -->
      </class> <!-- com.atmecs.EmployeeManagementTest.StoryRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
