<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="3743" started-at="2014-06-12T17:12:44Z" finished-at="2014-06-12T17:12:48Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="3743" started-at="2014-06-12T17:12:44Z" finished-at="2014-06-12T17:12:48Z">
      <class name="com.atmecs.EmployeeManagementTest.StoryRunner">
        <test-method status="FAIL" signature="run()[pri:0, instance:com.atmecs.EmployeeManagementTest.StoryRunner@5d1f1d6]" name="run" duration-ms="3732" started-at="2014-06-12T17:12:44Z" finished-at="2014-06-12T17:12:48Z">
          <exception class="org.jbehave.core.embedder.Embedder$RunningStoriesFailed">
            <message>
              <![CDATA[Failures in running stories: ReportsCount[stories=1,storiesNotAllowed=0,storiesPending=0,scenarios=58,scenariosFailed=55,scenariosNotAllowed=0,scenariosPending=0,stepsFailed=55]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: ReportsCount[stories=1,storiesNotAllowed=0,storiesPending=0,scenarios=58,scenariosFailed=55,scenariosNotAllowed=0,scenariosPending=0,stepsFailed=55]
	at org.jbehave.core.embedder.Embedder$ThrowingRunningStoriesFailed.handleFailures(Embedder.java:525)
	at org.jbehave.core.embedder.Embedder.handleFailures(Embedder.java:269)
	at org.jbehave.core.embedder.Embedder.generateReportsView(Embedder.java:256)
	at org.jbehave.core.embedder.Embedder.generateReportsView(Embedder.java:237)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
	at org.jbehave.core.junit.JUnitStory.run(JUnitStory.java:24)
	at com.atmecs.EmployeeManagementTest.StoryRunner.run(StoryRunner.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
